name: hadieaty
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animations: ^2.0.11
  circle_nav_bar: ^2.2.0
  cloud_firestore: ^5.6.7
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/

  fonts:
    - family: FREESCPT
      fonts:
        - asset: assets/fonts/FREESCPT/FREESCPT.ttf
    - family: Play
      fonts:
        - asset: assets/fonts/Play/Play-Bold.ttf
        - asset: assets/fonts/Play/Play-Regular.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  background_color: "#ffffff"
  theme_color: "#ffffff"
  image_path: "assets/imgs/logo_full.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
